[package]
name = "wtlfu"
version = "0.1.0"
authors = ["Luca Fulchir <luker@fenrirproject.org>"]
edition = "2018"
description = "Window Tiny LFU implementation"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

thiserror = "1.0"
bitfield = "0.13"
bitvec = "0.21"
hashbrown = "0.11"
num-traits = "0.2"

